module.exports = {
    API_POST_PUT_CANCEL_TASK: '/help/task/cancelTask',
    API_POST_PUT_ABANDON_TASK: '/help/task-receive/abandonTask',
    API_POST_PUT_COMMENT: '/help/task-comment/comment',
    API_POST_GET_COMMENT: '/help/task-comment/searchCommentByTaskId',
    API_POST_GET_SEARCH_USER: '/help/user/searchByNick',
    API_POST_PUT_UPDATE_INFO: '/help/user/update',
    API_POST_GET_LUNXUN: '/help/chat-record/getNewHistoryChat',
    API_POST_PUT_SEND_MESSAGE: '/help/chat-record/sendMessage',
    API_POST_GET_HISTORY_CHAT: '/help/chat-record/searchHistoryChat',
    API_POST_GET_RECEIVE_TASK: '/help/task-receive/searchReceiveTask',
    API_POST_GET_PUBLISH_TASK: '/help/task/searchPublishTask',
    API_POST_PUT_COMPLETE_TASK: '/help/task-receive/completeTask',
    API_POST_PUT_CONFIRM_TASK: '/help/task/confirmTask',
    API_POST_GET_USER_BY_ID: '/help/user/searchById',
    API_POST_GET_GET_TASK_BY_ID: '/help/task/searchTaskByTaskId',
    API_POST_PUT_RECEIVE_TASK: '/help/task-receive/receiveTask',
    API_POST_PUT_REGISTER: '/help/user/register',
    API_POST_PUT_PUBLISH_TASK: '/help/task/publishTask',
    API_GET_GET_SEARCH_TASK: '/help/task/searchTask',
    API_POST_LOGIN:'/help/user/login',
    API_POST_REGISTER:'/register',
    API_POST_GET_CIRCLE_LIST_BY_USER:'/circle/getCircleListByUser',
    API_POST_GET_TASK_BY_CIRCLE:'/task/getTasksByCircle',
    API_POST_ADD_TASK:'/task/addTask',
    API_POST_GET_TASK_BY_GET:'/task/getTaskByUserGet',
    API_POST_GET_TASK_BY_POST:'/task/getTaskByUserPost',
    API_POST_PUT_ACCEPT_TASK:'/task/acceptTask',
    API_POST_PUT_CREATE_CIRCLE:'/circle/createCircle',
    API_POST_GET_CIRCLE_BY_NAME:'/circle/searchCircleByName',
    API_POST_PUT_JOIN_CIRCLE:'/circle/addCircle',
    API_POST_FLAG_JOIN_CIRCLE:'/circle/getUserCircle',
    API_POST_DELETE_TASK:'/task/deleteTask'
}